name: docker script

on:
  push: # push 到主分支自动 发布
    branches: ["main"]
    paths-ignore: # 忽略一些不必要的文件
      - ".gitignore"
      - "README.md"
      - ".vscode/**"
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
        #使用默认环境
    environment: default
    env:
        S3_AK: ${{ vars.S3_AK }}
        S3_EP: ${{ vars.S3_EP }}
        S3_SK: ${{ vars.S3_SK }}
        ALICLOUD_ACCESS_KEY: ${{ vars.ALICLOUD_ACCESS_KEY }}
        ALICLOUD_SECRET_KEY: ${{ vars.ALICLOUD_SECRET_KEY }}
        CLOUDFLARE_DNS_API_TOKEN: ${{ vars.CLOUDFLARE_DNS_API_TOKEN }}
        DNSPOD_API_KEY: ${{ vars.DNSPOD_API_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: docker build
        run: |
          docker build . --file Dockerfile --tag ci-image:latest
          env
      - name: run docker script
        run: |
          docker run --rm -i \
          -e S3_AK=$S3_AK \
          -e S3_EP=$S3_EP \
          -e S3_SK=$S3_SK \
          -e ALICLOUD_ACCESS_KEY=$ALICLOUD_ACCESS_KEY \
          -e ALICLOUD_SECRET_KEY=$ALICLOUD_SECRET_KEY \
          -e CLOUDFLARE_DNS_API_TOKEN=$CLOUDFLARE_DNS_API_TOKEN \
          -e DNSPOD_API_KEY=$DNSPOD_API_KEY \
          ci-image:latest ppp.ssl.lyhepj.cn,ttt.ssl.lyhepj.cn
